using System;
using System.Collections.Generic;
using System.Text;

namespace Dota_2_Console_App.Enums
{
    public enum Hero
    {
        AntiMage = 1,
        Axe,
        Bane,
        Bloodseeker,
        CrystalMaiden,
        DrowRanger,
        Earthshaker,
        Juggernaut,
        Mirana,
        Morphling,
        ShadowFiend,
        PhantomLancer,
        Puck,
        Pudge,
        Razor,
        SandKing,
        StormSpirit,
        Sven,
        Tiny,
        VengefulSpirit,
        WindRanger,
        Zeus,
        Kunkka,
        Lina = 25,
        Lion,
        ShadowShaman,
        Slardar,
        Tidehunter,
        WitchDoctor,
        Lich,
        Riki,
        Enigma,
        Tinker,
        Sniper,
        Necrophos,
        Warlock,
        Beastmaster,
        QueenOfPain,
        Venomancer,
        FacelessVoid,
        WraithKing,
        DeathProphet,
        PhantomAssassin,
        Pugna,
        TemplarAssasin,
        Viper,
        Luna,
        DragonKnight,
        Dazzle,
        Clockwerk,
        Leshrac,
        NatureProphet,
        Lifestealer,
        DarkSeer,
        Clinkz,
        Omniknight,
        Enchantress,
        Huskar,
        NightStalker,
        Broodmother,
        BountyHunter,
        Weawer,
        Jakiro,
        Batrider,
        Chen,
        Spectre,
        AncientApparition,
        Doom,
        Ursa,
        SpiritBreaker,
        Gyrocopter,
        Alchemist,
        Invoker,
        Silencer,
        OutworldDestroyer,
        Lycan,
        Brewmaster,
        ShadowDemon,
        LoneDruid,
        ChaosKnight,
        Meepo,
        TreantProtector,
        OgreMagi,
        Undying,
        Rubick,
        Disruptor,
        NyxAssassin,
        NagaSiren,
        KeeperOfTheLight,
        Io,
        Visage,
        Slark,
        Medusa,
        TrollWarlord,
        CentaurWarrunner,
        Magnus,
        Timbersaw,
        Bristleback,
        Tusk,
        SkywraithMage,
        Abaddon,
        ElderTitan,
        LegionCommander,
        Techies,
        EmberSpirit,
        EarthSpirit,
        Underlord,
        Terrorblade,
        Phoenix,
        Oracle,
        WinterWyvern,
        ArcWarden,
        MonkeyKing,
        DarkWillow = 119,
        Pangolier,
        Grimstroke,
        Hoodwink = 123,
        Voidspirit = 126,
        Snapfire = 128,
        Mars = 129,
        Dawnbreaker = 135
    }
}
